language: node_js
node_js:
- node


notifications:
  email: false


services:
- docker

env:
  global:
    secure: YaH2+sUAXvkV9tm99VYxCcPzrhJMRdpoDQ+QqqYIH4huA0DvQnjwJ8NPG7Uym2EX1L7dbL11/+UCs4ycD/oNOKajN+mbBUTe0hyXvxHk8y8k7IGLUAm++OYYXEJ/Vkc4i3mKvUfUg68NIqQ9y9X98ERer7wIyhMtrfwPijiJwRmdgbp8L1Y7BbMLoVgAqvhm5aJX8hxTCX/idySCkn1oBPWYe73kKyYIVzjmEjHZYWeCUFY0ArGDd9s6oT3g6XKuVKpYUQfZkDO9WVWFkqpj/lJ6vou+xWRkJfd+lK+rLiz++ikGQb+TD8BpifApSt6DecB1xeQXWQhjVFkiBZQhc+w/uk579WxnjmNN7iGJSvcF4U+v0oqKzDoKT3ouLyGQ4bPkv7jmjTO9+FPmzpoZ8yPvcqoyIKOGLtXLp4IVbA2bkVISnEE6c2/Pvys6Pp8uXWA9ZdBHDITbXwyA8sqPbcjQFJ/fqepsNhpnXCoxNy6pKWv9UL9AQwOsb7foKiT9vI9RfvDA3mtziSCyo5MU6g3Wrb13t90cudAW8kXG5lRQLlSoBludAzIo0pgszneqalL3ER6ufuvUkn6W8boChZspiT6Bzi6sJ1sY3VrQNVIA1MFVteYTL1KIRVNqwlMwvnlkkjqrZ9AfSY7lkNp/5MoBS6BXzA1M/pd8DStN/XA=


before_install:
- sudo /etc/init.d/postgresql stop
- COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-7)
- IMAGE_TAG=${COMMIT_HASH:=latest}
- echo $IMAGE_TAG
script:
- echo Testing started on `date`
- echo Testing the Docker image...
- docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from
  api --build
- echo Build started on `date`
- echo Building the Docker image...
- APP_NAME="$(cut -d'/' -f2 <<< $TRAVIS_REPO_SLUG)"
- DOCKER_USERNAME="leevilehtonen"
- docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
- docker build -t $DOCKER_USERNAME/$APP_NAME:latest .
- docker tag $DOCKER_USERNAME/$APP_NAME:latest registry.heroku.com/$APP_NAME/web
- docker push registry.heroku.com/$APP_NAME/web
- heroku container:release web --app=$APP_NAME
  
