language: node_js
node_js:
  - node
notifications:
  email: false

services:
  - docker

before_install:
  - COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-7)
  - IMAGE_TAG=${COMMIT_HASH:=latest}
  - echo $IMAGE_TAG

script:
  - echo Testing started on `date`
  - echo Testing the Docker image... 
  - docker version
  - docker-compose version
  - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from api --build
  - echo Build started on `date`
  - echo Building the Docker image...          
  - docker build -t $IMAGE_REPO_URL:latest .
  - docker tag $IMAGE_REPO_URL:latest $IMAGE_REPO_URL:$IMAGE_TAG     
