language: node_js
node_js:
- node
notifications:
  email: false
services:
- docker
before_install:
- sudo /etc/init.d/postgresql stop
- COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-7)
- IMAGE_TAG=${COMMIT_HASH:=latest}
- echo $IMAGE_TAG
script:
- echo Testing started on `date`
- echo Testing the Docker image...
- docker version
- docker-compose version
- docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from
  api --build
- echo Build started on `date`
- echo Building the Docker image...
- IMAGE_NAME="$(cut -d'/' -f2 <<< $TRAVIS_REPO_SLUG)"
- DOCKER_USERNAME="leevilehtonen"
- heroku
- docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
- docker tag $DOCKER_USERNAME/$IMAGE_NAME:latest registry.heroku.com/$IMAGE_NAME/web
- docker push registry.heroku.com/$IMAGE_NAME/web

deploy:
  provider: heroku
  api_key:
    secure: mek989aQYSKrX1ANCiz4NCASt/KJeecXNOR+WnV9ZDwL/zqMz8Jy1EdtL5j0JMLH3IFO0jTuHtfZ8bAczhD6NIn/iomSwV2STUQPjEvCb2YXeAfxHIITgbEr+ML8hwCO4CKMyUjV0jG497iHxbozUbfKPuDH0yIDHdOaAuWFlw64BZynyzSeV04GAVaKYp9TQIOKXAsvOjbECg3L5lVpwBGsDmmG8tuXdwq0uHtdOKcmuTZQ+ESFP3DCDc79pchCqJp7/I49e5prXV/oaaSD61dgltiYQdUG9ydvYO+oLiXTk6Ehu4vKlM/Q243rWqqyJzW4eBH3JUVCi2BSNuSzaIvGi4WVSqY1OZBRNdvH86CKyELIKJQhd+yR+eCtoy4cYK8k+kLv+7RCGQL+wCYOFi6AvqS2UOu0VMRn2pR2xXH5yi877DBtfyfU29HDx7qAkAvumF4Ms/X9fX2wvv2eVCpw7bdHoDF/mhEIbqjJfDEXJQ06wU15w75tQlCgzyPSHrcyepgUfIUsGuK8BTvZhumGLfEhXxIyA5/5g9B+Ue2gix4buggBfLyOdDQVW21AJC3cxHUOikitUfx8UUrCZgSu6v+Ey8bWhmqvzRwwFAC4+8nwvTylA/hSMrK/GYuXokJE7C3YoVRxXM8tSZk6pjIkwsXaDBU6VjloF4OAHpE=
  app: flashcardify-quiz-service
  on:
    repo: leevilehtonen/flashcardify-quiz-service
