language: node_js
node_js:
  - node
notifications:
  email: false

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-7)
  - IMAGE_TAG=${COMMIT_HASH:=latest}
  - echo $IMAGE_TAG

script:
  - echo Testing started on `date`
  - echo Testing the Docker image... 
  - docker version
  - docker-compose version
  - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from api --build
  - echo Build started on `date`
  - echo Building the Docker image...
  - IMAGE_NAME="$(cut -d'/' -f2 <<< $TRAVIS_REPO_SLUG)"
  - DOCKER_USERNAME="leevilehtonen"
  - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
  - docker tag $DOCKER_USERNAME/$IMAGE_NAME:latest $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG     
