language: node_js
node_js:
- node
notifications:
  email: false
services:
- docker
env:
  global:
  - secure: P6Ldz4f+K2u3+oITBvqS73Jc0xqAfHI5ZbRJe1WbGW1U9wP8mxCinDTbDip+24ALD337xnnr6OmUakzOwlQTzeY3BEGPpfgGi7NU3WII0feOwPjP6jAygYScaG4us11XSAcLrx1DqoGXPxn1iyqfkbPP+q38tV8tmxruzlnBdoQtiulHMm7lpvb8kGPSMJVbMM6JGQd73qRT7HDl7kT5BEo4/hVQhOru4DKEHywmFe+R5UCyaSLlTnDptBqoU6FyNVvstHM9ZTCxjameTWLxZv5k+yk8IlShVE9V33LD62etcBUSkfzTBNW4zJxfIMPYyTXUjV5/YJUJpmUJyDeVAKVTe5r5rEudyLWWbvIBS72Z0/FtFopSPyJSNpQCwg3LUTzM8SUWaskZV3/rglYgy+3PH3kU1M+uaTdF94cXePXjzvUFip8DP8YCBQ6SVkQCwKCeeYF/hr7Pog6LLzgTW+Ur4VHXwXQzGcykfcBBBPc04f2ggy58jAvpIYVudBD0StG1qCxjTgoFeQNKbUXEEuWlIp7e3Xx1owV9vkm+O5mIjhfbmaD/ZES3ns/+MNUUg9gYr4BMR43MGfFmO/EhKIQ+0UXD31rOWoqf+PVRS6bL+ou484FueIo05B24XSEfvG23dWOgW7PYy2XjS1PIYp982iiP3GytJ2b1pWqKRNw=
before_install:
- sudo /etc/init.d/postgresql stop
- COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -c 1-7)
- IMAGE_TAG=${COMMIT_HASH:=latest}
- echo $IMAGE_TAG
script:
- echo Testing started on `date`
- echo Testing the Docker image...
- docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from
  api --build
- echo Build started on `date`
- echo Building the Docker image...
- APP_NAME="$(cut -d'/' -f2 <<< $TRAVIS_REPO_SLUG)"
- DOCKER_USERNAME="leevilehtonen"
- heroku container:login
- docker build -t $DOCKER_USERNAME/$APP_NAME:latest .
- docker tag $DOCKER_USERNAME/$APP_NAME:latest registry.heroku.com/$APP_NAME/web
- docker push registry.heroku.com/$APP_NAME/web

deploy:
  - provider: script
    script: heroku container:release web --app=$APP_NAME
    on:
      branch: master

