version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG
      - echo $IMAGE_REPO_URL
  build:
    commands:
      - echo Testing started on `date`
      - echo Testing the Docker image... 
      - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from api --build
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_URL:latest .
      - docker tag $IMAGE_REPO_URL:latest $IMAGE_REPO_URL:$IMAGE_TAG     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo $IMAGE_TAG
      - echo $IMAGE_REPO_URL
      - docker push $IMAGE_REPO_URL:latest
      - docker push $IMAGE_REPO_URL:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_NAME $IMAGE_REPO_URL:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json